global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nodejs-app'
    metrics_path: '/actuator/prometheus'
    scheme: https
    static_configs:
      - targets: ['home-task-5-production-63e8.up.railway.app']
